// Auto-generated by TerritoryLookup.ExportStaticMap
// Source: TerritoryType + (ContentFinderCondition | QuestBattle? | PublicContent? | InstanceContent?)
// Generated on 9/19/25 for patch 7.3
#nullable enable
using System;
using System.Collections.Generic;
namespace TerritoryTools
{
    public static class TerritoryStaticMap
    {
        public static List<uint> TownTerritoryIds { get; set; } = new List<uint>([128, 129, 130, 131, 132, 133, 144, 
            388, 418, 419, 478, 635, 628, 759, 819, 820, 962, 963, 1185, 1186]);
        public static bool IsTown(uint id) => TownTerritoryIds.Contains(id);
        /// <summary> true = instanced; false = open-world; null = unknown id </summary>
        public static bool? IsInstance(uint territoryId) => _map.TryGetValue(territoryId, out var v) ? v : (bool?)null;
        public static IReadOnlyDictionary<uint, bool> Map => _map;
        private static readonly Dictionary<uint, bool> _map = new()
        {
            // Territory #1
            [1] = false,
            // Territory #2
            [2] = false,
            // Territory #3
            [3] = false,
            // Territory #4
            [4] = false,
            // Territory #5
            [5] = false,
            // Territory #6
            [6] = false,
            // Territory #7
            [7] = false,
            // Territory #8
            [8] = false,
            // Territory #9
            [9] = false,
            // Territory #10
            [10] = false,
            // Territory #11
            [11] = false,
            // Territory #12
            [12] = false,
            // Territory #13
            [13] = false,
            // Territory #14
            [14] = false,
            // Territory #15
            [15] = false,
            // Territory #16
            [16] = false,
            // Territory #17
            [17] = false,
            // Territory #18
            [18] = false,
            // Territory #19
            [19] = false,
            // Territory #20
            [20] = false,
            // Territory #21
            [21] = false,
            // Territory #22
            [22] = false,
            // Territory #24
            [24] = false,
            // Territory #25
            [25] = false,
            // Territory #26
            [26] = false,
            // Territory #27
            [27] = false,
            // Territory #28
            [28] = false,
            // Territory #29
            [29] = false,
            // Territory #30
            [30] = false,
            // Territory #31
            [31] = false,
            // Limsa Lominsa Upper Decks
            [128] = false,
            // Limsa Lominsa Lower Decks
            [129] = false,
            // Ul'dah - Steps of Nald
            [130] = false,
            // Ul'dah - Steps of Thal
            [131] = false,
            // New Gridania
            [132] = false,
            // Old Gridania
            [133] = false,
            // Middle La Noscea
            [134] = false,
            // Lower La Noscea
            [135] = false,
            // Mist
            [136] = false,
            // Eastern La Noscea
            [137] = false,
            // Western La Noscea
            [138] = false,
            // Upper La Noscea
            [139] = false,
            // Western Thanalan
            [140] = false,
            // Central Thanalan
            [141] = false,
            // Halatali
            [142] = true,
            // Territory #143
            [143] = false,
            // The Gold Saucer
            [144] = false,
            // Eastern Thanalan
            [145] = false,
            // Southern Thanalan
            [146] = false,
            // Northern Thanalan
            [147] = false,
            // Central Shroud
            [148] = false,
            // The Feasting Grounds
            [149] = false,
            // Territory #150
            [150] = false,
            // The World of Darkness
            [151] = true,
            // East Shroud
            [152] = false,
            // South Shroud
            [153] = false,
            // North Shroud
            [154] = false,
            // Coerthas Central Highlands
            [155] = false,
            // Mor Dhona
            [156] = false,
            // Territory #157
            [157] = false,
            // Territory #158
            [158] = false,
            // The Wanderer's Palace
            [159] = true,
            // Pharos Sirius
            [160] = true,
            // Territory #161
            [161] = false,
            // Territory #162
            [162] = false,
            // Territory #163
            [163] = false,
            // Territory #164
            [164] = false,
            // Territory #166
            [166] = false,
            // Amdapor Keep
            [167] = true,
            // Territory #168
            [168] = false,
            // Territory #169
            [169] = false,
            // Territory #170
            [170] = false,
            // Dzemael Darkhold
            [171] = true,
            // Aurum Vale
            [172] = true,
            // Labyrinth of the Ancients
            [174] = true,
            // Territory #175
            [175] = false,
            // Mordion Gaol
            [176] = true,
            // Mizzenmast Inn
            [177] = true,
            // The Hourglass
            [178] = true,
            // The Roost
            [179] = true,
            // Outer La Noscea
            [180] = false,
            // Limsa Lominsa
            [181] = false,
            // Ul'dah - Steps of Nald
            [182] = false,
            // New Gridania
            [183] = false,
            // Territory #184
            [184] = false,
            // Territory #185
            [185] = false,
            // Territory #186
            [186] = false,
            // Territory #187
            [187] = false,
            // The Wanderer's Palace
            [188] = true,
            // Amdapor Keep
            [189] = true,
            // Central Shroud
            [190] = true,
            // East Shroud
            [191] = true,
            // South Shroud
            [192] = true,
            // IC-06 Central Decks
            [193] = true,
            // IC-06 Regeneration Grid
            [194] = true,
            // IC-06 Main Bridge
            [195] = true,
            // The Burning Heart
            [196] = true,
            // Territory #197
            [197] = false,
            // Command Room
            [198] = false,
            // Territory #199
            [199] = false,
            // Territory #200
            [200] = false,
            // Territory #201
            [201] = false,
            // Territory #202
            [202] = false,
            // Territory #203
            [203] = false,
            // Seat of the First Bow
            [204] = false,
            // Lotus Stand
            [205] = false,
            // Territory #206
            [206] = false,
            // Territory #207
            [207] = false,
            // Territory #208
            [208] = false,
            // Territory #209
            [209] = false,
            // Heart of the Sworn
            [210] = false,
            // Territory #211
            [211] = false,
            // The Waking Sands
            [212] = false,
            // Territory #213
            [213] = false,
            // Middle La Noscea
            [214] = true,
            // Western Thanalan
            [215] = true,
            // Central Thanalan
            [216] = true,
            // Territory #217
            [217] = false,
            // Territory #218
            [218] = false,
            // Central Shroud
            [219] = true,
            // South Shroud
            [220] = true,
            // Upper La Noscea
            [221] = true,
            // Lower La Noscea
            [222] = true,
            // Coerthas Central Highlands
            [223] = true,
            // Territory #224
            [224] = false,
            // Central Shroud
            [225] = true,
            // Central Shroud
            [226] = true,
            // Central Shroud
            [227] = true,
            // North Shroud
            [228] = true,
            // South Shroud
            [229] = true,
            // Central Shroud
            [230] = true,
            // South Shroud
            [231] = true,
            // South Shroud
            [232] = true,
            // Central Shroud
            [233] = true,
            // East Shroud
            [234] = true,
            // South Shroud
            [235] = true,
            // South Shroud
            [236] = true,
            // Central Shroud
            [237] = true,
            // Old Gridania
            [238] = true,
            // Central Shroud
            [239] = true,
            // North Shroud
            [240] = true,
            // Upper Aetheroacoustic Exploratory Site
            [241] = true,
            // Lower Aetheroacoustic Exploratory Site
            [242] = true,
            // The Ragnarok
            [243] = true,
            // Ragnarok Drive Cylinder
            [244] = true,
            // Ragnarok Central Core
            [245] = true,
            // IC-04 Main Bridge
            [246] = false,
            // Ragnarok Main Bridge
            [247] = false,
            // Central Thanalan
            [248] = true,
            // Lower La Noscea
            [249] = true,
            // Wolves' Den Pier
            [250] = false,
            // Ul'dah - Steps of Nald
            [251] = true,
            // Middle La Noscea
            [252] = true,
            // Central Thanalan
            [253] = true,
            // Ul'dah - Steps of Nald
            [254] = true,
            // Western Thanalan
            [255] = true,
            // Eastern Thanalan
            [256] = true,
            // Eastern Thanalan
            [257] = true,
            // Central Thanalan
            [258] = true,
            // Ul'dah - Steps of Nald
            [259] = true,
            // Southern Thanalan
            [260] = true,
            // Southern Thanalan
            [261] = true,
            // Lower La Noscea
            [262] = true,
            // Western La Noscea
            [263] = true,
            // Lower La Noscea
            [264] = true,
            // Lower La Noscea
            [265] = true,
            // Eastern Thanalan
            [266] = true,
            // Western Thanalan
            [267] = true,
            // Eastern Thanalan
            [268] = true,
            // Western Thanalan
            [269] = true,
            // Central Thanalan
            [270] = true,
            // Central Thanalan
            [271] = true,
            // Middle La Noscea
            [272] = true,
            // Western Thanalan
            [273] = true,
            // Ul'dah - Steps of Nald
            [274] = true,
            // Eastern Thanalan
            [275] = true,
            // Hall of Summoning
            [276] = false,
            // East Shroud
            [277] = true,
            // Western Thanalan
            [278] = true,
            // Lower La Noscea
            [279] = true,
            // Western La Noscea
            [280] = true,
            // The Whorleater
            [281] = true,
            // Private Cottage - Mist
            [282] = false,
            // Private House - Mist
            [283] = false,
            // Private Mansion - Mist
            [284] = false,
            // Middle La Noscea
            [285] = true,
            // Rhotano Sea
            [286] = true,
            // Lower La Noscea
            [287] = true,
            // Rhotano Sea
            [288] = true,
            // East Shroud
            [289] = true,
            // East Shroud
            [290] = true,
            // South Shroud
            [291] = true,
            // Bowl of Embers
            [292] = true,
            // The Navel
            [293] = true,
            // The Howling Eye
            [294] = true,
            // Bowl of Embers
            [295] = true,
            // The Navel
            [296] = true,
            // The Howling Eye
            [297] = true,
            // Coerthas Central Highlands
            [298] = true,
            // Mor Dhona
            [299] = true,
            // Mor Dhona
            [300] = true,
            // Coerthas Central Highlands
            [301] = true,
            // Coerthas Central Highlands
            [302] = true,
            // East Shroud
            [303] = true,
            // Coerthas Central Highlands
            [304] = true,
            // Mor Dhona
            [305] = true,
            // Southern Thanalan
            [306] = true,
            // Lower La Noscea
            [307] = true,
            // Mor Dhona
            [308] = true,
            // Mor Dhona
            [309] = true,
            // Eastern La Noscea
            [310] = true,
            // Eastern La Noscea
            [311] = true,
            // Southern Thanalan
            [312] = true,
            // Coerthas Central Highlands
            [313] = true,
            // Central Thanalan
            [314] = true,
            // Mor Dhona
            [315] = true,
            // Coerthas Central Highlands
            [316] = true,
            // South Shroud
            [317] = true,
            // Southern Thanalan
            [318] = true,
            // Central Shroud
            [319] = true,
            // Central Shroud
            [320] = true,
            // North Shroud
            [321] = true,
            // Coerthas Central Highlands
            [322] = true,
            // Southern Thanalan
            [323] = true,
            // North Shroud
            [324] = true,
            // Outer La Noscea
            [325] = true,
            // Mor Dhona
            [326] = true,
            // Eastern La Noscea
            [327] = true,
            // Upper La Noscea
            [328] = true,
            // The Wanderer's Palace
            [329] = true,
            // Western La Noscea
            [330] = true,
            // The Howling Eye
            [331] = false,
            // Territory #332
            [332] = false,
            // Territory #333
            [333] = false,
            // Territory #334
            [334] = false,
            // Mor Dhona
            [335] = false,
            // Territory #336
            [336] = false,
            // Territory #337
            [337] = false,
            // Eorzean Subterrane
            [338] = false,
            // Mist
            [339] = false,
            // The Lavender Beds
            [340] = false,
            // The Goblet
            [341] = false,
            // Private Cottage - The Lavender Beds
            [342] = false,
            // Private House - The Lavender Beds
            [343] = false,
            // Private Mansion - The Lavender Beds
            [344] = false,
            // Private Cottage - The Goblet
            [345] = false,
            // Private House - The Goblet
            [346] = false,
            // Private Mansion - The Goblet
            [347] = false,
            // Porta Decumana
            [348] = true,
            // Copperbell Mines
            [349] = true,
            // Haukke Manor
            [350] = true,
            // The Rising Stones
            [351] = false,
            // Territory #352
            [352] = false,
            // Kugane Ohashi
            [353] = true,
            // The Dancing Plague
            [354] = true,
            // Dalamud's Shadow
            [355] = true,
            // The Outer Coil
            [356] = true,
            // Central Decks
            [357] = true,
            // The Holocharts
            [358] = true,
            // The Whorleater
            [359] = true,
            // Halatali
            [360] = true,
            // Hullbreaker Isle
            [361] = true,
            // Brayflox's Longstop
            [362] = true,
            // The Lost City of Amdapor
            [363] = true,
            // Thornmarch
            [364] = true,
            // Stone Vigil
            [365] = true,
            // Griffin Crossing
            [366] = true,
            // The Sunken Temple of Qarn
            [367] = true,
            // The Weeping Saint
            [368] = true,
            // Hall of the Bestiarii
            [369] = true,
            // Main Bridge
            [370] = false,
            // Territory #371
            [371] = false,
            // Syrcus Tower
            [372] = true,
            // The Tam-Tara Deepcroft
            [373] = true,
            // The Striking Tree
            [374] = true,
            // The Striking Tree
            [375] = true,
            // Carteneau Flats: Borderland Ruins
            [376] = false,
            // Akh Afah Amphitheatre
            [377] = true,
            // Akh Afah Amphitheatre
            [378] = true,
            // Mor Dhona
            [379] = true,
            // Dalamud's Shadow
            [380] = true,
            // The Outer Coil
            [381] = true,
            // Central Decks
            [382] = true,
            // The Holocharts
            [383] = true,
            // Private Chambers - Mist
            [384] = false,
            // Private Chambers - The Lavender Beds
            [385] = false,
            // Private Chambers - The Goblet
            [386] = false,
            // Sastasha
            [387] = true,
            // Chocobo Square
            [388] = false,
            // Chocobo Square
            [389] = true,
            // Chocobo Square
            [390] = true,
            // Chocobo Square
            [391] = true,
            // Sanctum of the Twelve
            [392] = false,
            // Sanctum of the Twelve
            [393] = false,
            // South Shroud
            [394] = true,
            // Intercessory
            [395] = false,
            // Amdapor Keep
            [396] = true,
            // Coerthas Western Highlands
            [397] = false,
            // The Dravanian Forelands
            [398] = false,
            // The Dravanian Hinterlands
            [399] = false,
            // The Churning Mists
            [400] = false,
            // The Sea of Clouds
            [401] = false,
            // Azys Lla
            [402] = false,
            // Ala Mhigo
            [403] = true,
            // Limsa Lominsa Lower Decks
            [404] = true,
            // Western La Noscea
            [405] = true,
            // Western La Noscea
            [406] = true,
            // Rhotano Sea
            [407] = true,
            // Eastern La Noscea
            [408] = true,
            // Limsa Lominsa Upper Decks
            [409] = true,
            // Northern Thanalan
            [410] = true,
            // Eastern La Noscea
            [411] = true,
            // Upper La Noscea
            [412] = true,
            // Western La Noscea
            [413] = true,
            // Eastern La Noscea
            [414] = true,
            // Lower La Noscea
            [415] = true,
            // Territory #416
            [416] = false,
            // Chocobo Square
            [417] = true,
            // Foundation
            [418] = false,
            // The Pillars
            [419] = false,
            // Neverreap
            [420] = true,
            // Territory #421
            [421] = false,
            // Territory #422
            [422] = false,
            // Company Workshop - Mist
            [423] = true,
            // Company Workshop - The Goblet
            [424] = true,
            // Company Workshop - The Lavender Beds
            [425] = true,
            // The Chrysalis
            [426] = true,
            // Saint Endalim's Scholasticate
            [427] = false,
            // Seat of the Lord Commander
            [428] = false,
            // Cloud Nine
            [429] = true,
            // The Fractal Continuum
            [430] = true,
            // Seal Rock
            [431] = true,
            // Thok ast Thok
            [432] = true,
            // Fortemps Manor
            [433] = false,
            // Dusk Vigil
            [434] = true,
            // Territory #435
            [435] = false,
            // The Limitless Blue
            [436] = true,
            // Singularity Reactor
            [437] = true,
            // Territory #438
            [438] = false,
            // The Lightfeather Proving Grounds
            [439] = false,
            // Ruling Chamber
            [440] = false,
            // Territory #441
            [441] = false,
            // The Fist of the Father
            [442] = true,
            // The Cuff of the Father
            [443] = true,
            // The Arm of the Father
            [444] = true,
            // The Burden of the Father
            [445] = true,
            // Thok ast Thok
            [446] = true,
            // The Limitless Blue
            [447] = true,
            // Singularity Reactor
            [448] = true,
            // The Fist of the Father
            [449] = true,
            // The Cuff of the Father
            [450] = true,
            // The Arm of the Father
            [451] = true,
            // The Burden of the Father
            [452] = true,
            // Western La Noscea
            [453] = true,
            // Upper La Noscea
            [454] = true,
            // The Sea of Clouds
            [455] = true,
            // Ruling Chamber
            [456] = true,
            // Akh Afah Amphitheatre
            [457] = true,
            // Foundation
            [458] = true,
            // Azys Lla
            [459] = true,
            // Halatali
            [460] = true,
            // The Sea of Clouds
            [461] = true,
            // Sacrificial Chamber
            [462] = false,
            // Matoya's Cave
            [463] = false,
            // The Dravanian Forelands
            [464] = true,
            // Eastern Thanalan
            [465] = true,
            // Upper La Noscea
            [466] = true,
            // Coerthas Western Highlands
            [467] = true,
            // Coerthas Central Highlands
            [468] = true,
            // Coerthas Central Highlands
            [469] = true,
            // Coerthas Western Highlands
            [470] = true,
            // Eastern La Noscea
            [471] = true,
            // Coerthas Western Highlands
            [472] = true,
            // South Shroud
            [473] = true,
            // Limsa Lominsa Upper Decks
            [474] = true,
            // Coerthas Central Highlands
            [475] = true,
            // The Dravanian Hinterlands
            [476] = true,
            // Coerthas Western Highlands
            [477] = true,
            // Idyllshire
            [478] = false,
            // Coerthas Western Highlands
            [479] = true,
            // Mor Dhona
            [480] = true,
            // The Dravanian Forelands
            [481] = true,
            // The Dravanian Forelands
            [482] = true,
            // Northern Thanalan
            [483] = true,
            // Lower La Noscea
            [484] = true,
            // The Dravanian Hinterlands
            [485] = true,
            // Outer La Noscea
            [486] = true,
            // Coerthas Central Highlands
            [487] = true,
            // Coerthas Central Highlands
            [488] = true,
            // Coerthas Western Highlands
            [489] = true,
            // Hullbreaker Isle
            [490] = true,
            // Southern Thanalan
            [491] = true,
            // The Sea of Clouds
            [492] = true,
            // Coerthas Western Highlands
            [493] = true,
            // Eastern Thanalan
            [494] = true,
            // Lower La Noscea
            [495] = true,
            // Coerthas Central Highlands
            [496] = true,
            // Coerthas Western Highlands
            [497] = true,
            // Coerthas Western Highlands
            [498] = true,
            // The Pillars
            [499] = true,
            // Coerthas Central Highlands
            [500] = true,
            // The Churning Mists
            [501] = true,
            // Carteneau Flats: Borderland Ruins
            [502] = true,
            // The Dravanian Hinterlands
            [503] = true,
            // The Eighteenth Floor
            [504] = false,
            // Alexander
            [505] = false,
            // Chocobo Square
            [506] = true,
            // Central Azys Lla
            [507] = false,
            // Void Ark
            [508] = true,
            // The Gilded Araya
            [509] = true,
            // Pharos Sirius
            [510] = true,
            // Saint Mocianne's Arboretum
            [511] = true,
            // The Diadem
            [512] = true,
            // The Vault
            [513] = true,
            // The Diadem
            [514] = true,
            // The Diadem
            [515] = true,
            // Territory #516
            [516] = false,
            // Containment Bay S1T7
            [517] = true,
            // Territory #518
            [518] = false,
            // The Lost City of Amdapor
            [519] = true,
            // The Fist of the Son
            [520] = true,
            // The Cuff of the Son
            [521] = true,
            // The Arm of the Son
            [522] = true,
            // The Burden of the Son
            [523] = true,
            // Containment Bay S1T7
            [524] = true,
            // Territory #525
            [525] = false,
            // Territory #526
            [526] = false,
            // Territory #527
            [527] = false,
            // Territory #528
            [528] = false,
            // The Fist of the Son
            [529] = true,
            // The Cuff of the Son
            [530] = true,
            // The Arm of the Son
            [531] = true,
            // The Burden of the Son
            [532] = true,
            // Coerthas Central Highlands
            [533] = true,
            // Twin Adder Barracks
            [534] = false,
            // Flame Barracks
            [535] = false,
            // Maelstrom Barracks
            [536] = false,
            // The Fold
            [537] = true,
            // The Fold
            [538] = true,
            // The Fold
            [539] = true,
            // The Fold
            [540] = true,
            // The Fold
            [541] = true,
            // The Fold
            [542] = true,
            // The Fold
            [543] = true,
            // The Fold
            [544] = true,
            // The Fold
            [545] = true,
            // The Fold
            [546] = true,
            // The Fold
            [547] = true,
            // The Fold
            [548] = true,
            // The Fold
            [549] = true,
            // The Fold
            [550] = true,
            // The Fold
            [551] = true,
            // Western La Noscea
            [552] = true,
            // Alexander
            [553] = false,
            // The Fields of Glory
            [554] = true,
            // Territory #555
            [555] = false,
            // The Weeping City of Mhach
            [556] = true,
            // Hullbreaker Isle
            [557] = true,
            // The Aquapolis
            [558] = true,
            // Steps of Faith
            [559] = true,
            // Aetherochemical Research Facility
            [560] = true,
            // The Palace of the Dead
            [561] = true,
            // The Palace of the Dead
            [562] = true,
            // The Palace of the Dead
            [563] = true,
            // The Palace of the Dead
            [564] = true,
            // The Palace of the Dead
            [565] = true,
            // Steps of Faith
            [566] = true,
            // The Parrock
            [567] = false,
            // Leofard's Chambers
            [568] = false,
            // Steps of Faith
            [569] = false,
            // The Palace of the Dead
            [570] = false,
            // Haunted Manor
            [571] = true,
            // Territory #572
            [572] = false,
            // Topmast Apartment Lobby
            [573] = false,
            // Lily Hills Apartment Lobby
            [574] = false,
            // Sultana's Breath Apartment Lobby
            [575] = false,
            // Containment Bay P1T6
            [576] = true,
            // Containment Bay P1T6
            [577] = true,
            // The Great Gubal Library
            [578] = true,
            // The Battlehall
            [579] = true,
            // Eyes of the Creator
            [580] = true,
            // Breath of the Creator
            [581] = true,
            // Heart of the Creator
            [582] = true,
            // Soul of the Creator
            [583] = true,
            // Eyes of the Creator
            [584] = true,
            // Breath of the Creator
            [585] = true,
            // Heart of the Creator
            [586] = true,
            // Soul of the Creator
            [587] = true,
            // Heart of the Creator
            [588] = false,
            // Chocobo Square
            [589] = true,
            // Chocobo Square
            [590] = true,
            // Chocobo Square
            [591] = true,
            // Bowl of Embers
            [592] = true,
            // The Palace of the Dead
            [593] = true,
            // The Palace of the Dead
            [594] = true,
            // The Palace of the Dead
            [595] = true,
            // The Palace of the Dead
            [596] = true,
            // The Palace of the Dead
            [597] = true,
            // The Palace of the Dead
            [598] = true,
            // The Palace of the Dead
            [599] = true,
            // The Palace of the Dead
            [600] = true,
            // The Palace of the Dead
            [601] = true,
            // The Palace of the Dead
            [602] = true,
            // The Palace of the Dead
            [603] = true,
            // The Palace of the Dead
            [604] = true,
            // The Palace of the Dead
            [605] = true,
            // The Palace of the Dead
            [606] = true,
            // The Palace of the Dead
            [607] = true,
            // Topmast Apartment
            [608] = false,
            // Lily Hills Apartment
            [609] = false,
            // Sultana's Breath Apartment
            [610] = false,
            // Frondale's Home for Friendless Foundlings
            [611] = false,
            // The Fringes
            [612] = false,
            // The Ruby Sea
            [613] = false,
            // Yanxia
            [614] = false,
            // Territory #615
            [615] = false,
            // Shisui of the Violet Tides
            [616] = true,
            // Sohm Al
            [617] = true,
            // Territory #618
            [618] = false,
            // Territory #619
            [619] = false,
            // The Peaks
            [620] = false,
            // The Lochs
            [621] = false,
            // The Azim Steppe
            [622] = false,
            // Territory #623
            [623] = false,
            // The Diadem
            [624] = true,
            // The Diadem
            [625] = true,
            // Territory #626
            [626] = false,
            // Dun Scaith
            [627] = true,
            // Kugane
            [628] = false,
            // Bokairo Inn
            [629] = false,
            // Territory #630
            [630] = true,
            // Territory #631
            [631] = false,
            // Territory #632
            [632] = false,
            // Carteneau Flats: Borderland Ruins
            [633] = true,
            // Yanxia
            [634] = true,
            // Rhalgr's Reach
            [635] = false,
            // Omega Control
            [636] = false,
            // Containment Bay Z1T9
            [637] = true,
            // Containment Bay Z1T9
            [638] = true,
            // Ruby Bazaar Offices
            [639] = false,
            // The Fringes
            [640] = true,
            // Shirogane
            [641] = false,
            // Territory #642
            [642] = false,
            // Territory #643
            [643] = false,
            // Territory #644
            [644] = false,
            // Territory #645
            [645] = false,
            // Territory #646
            [646] = false,
            // The Fringes
            [647] = true,
            // The Fringes
            [648] = true,
            // Private Cottage - Shirogane
            [649] = false,
            // Private House - Shirogane
            [650] = false,
            // Private Mansion - Shirogane
            [651] = false,
            // Private Chambers - Shirogane
            [652] = false,
            // Company Workshop - Shirogane
            [653] = true,
            // Kobai Goten Apartment Lobby
            [654] = false,
            // Kobai Goten Apartment
            [655] = false,
            // The Diadem
            [656] = true,
            // The Ruby Sea
            [657] = true,
            // The Interdimensional Rift
            [658] = true,
            // Rhalgr's Reach
            [659] = true,
            // Territory #660
            [660] = false,
            // Territory #661
            [661] = false,
            // Kugane Castle
            [662] = true,
            // The Temple of the Fist
            [663] = true,
            // Kugane
            [664] = true,
            // Kugane
            [665] = true,
            // Ul'dah - Steps of Thal
            [666] = true,
            // Kugane
            [667] = true,
            // Eastern Thanalan
            [668] = true,
            // Southern Thanalan
            [669] = true,
            // The Fringes
            [670] = true,
            // The Fringes
            [671] = true,
            // Mor Dhona
            [672] = true,
            // Sohm Al
            [673] = true,
            // The Blessed Treasury
            [674] = true,
            // Western La Noscea
            [675] = true,
            // The Great Gubal Library
            [676] = true,
            // The Blessed Treasury
            [677] = true,
            // The Fringes
            [678] = true,
            // The Royal Airship Landing
            [679] = true,
            // The Misery
            [680] = false,
            // The House of the Fierce
            [681] = false,
            // The Doman Enclave
            [682] = false,
            // The First Altar of Djanan Qhat
            [683] = false,
            // The Lochs
            [684] = true,
            // Yanxia
            [685] = true,
            // The Lochs
            [686] = true,
            // The Lochs
            [687] = true,
            // The Azim Steppe
            [688] = true,
            // Territory #689
            [689] = false,
            // The Interdimensional Rift
            [690] = true,
            // Deltascape V1.0
            [691] = true,
            // Deltascape V2.0
            [692] = true,
            // Deltascape V3.0
            [693] = true,
            // Deltascape V4.0
            [694] = true,
            // Deltascape V1.0
            [695] = true,
            // Deltascape V2.0
            [696] = true,
            // Deltascape V3.0
            [697] = true,
            // Deltascape V4.0
            [698] = true,
            // Coerthas Central Highlands
            [699] = true,
            // Foundation
            [700] = true,
            // Seal Rock
            [701] = true,
            // Aetherochemical Research Facility
            [702] = true,
            // The Fringes
            [703] = true,
            // Dalamud's Shadow
            [704] = true,
            // Ul'dah - Steps of Thal
            [705] = true,
            // Ul'dah - Steps of Thal
            [706] = true,
            // The Weeping City of Mhach
            [707] = true,
            // Rhotano Sea
            [708] = true,
            // Coerthas Western Highlands
            [709] = true,
            // Kugane
            [710] = true,
            // The Ruby Sea
            [711] = true,
            // The Lost Canals of Uznair
            [712] = true,
            // The Azim Steppe
            [713] = true,
            // Bardam's Mettle
            [714] = true,
            // The Churning Mists
            [715] = true,
            // The Peaks
            [716] = true,
            // Wolves' Den Pier
            [717] = true,
            // The Azim Steppe
            [718] = true,
            // Emanation
            [719] = true,
            // Emanation
            [720] = true,
            // Amdapor Keep
            [721] = true,
            // The Lost City of Amdapor
            [722] = true,
            // The Azim Steppe
            [723] = true,
            // The Interdimensional Rift
            [724] = false,
            // The Lost Canals of Uznair
            [725] = true,
            // The Ruby Sea
            [726] = true,
            // The Royal Menagerie
            [727] = false,
            // Mordion Gaol
            [728] = false,
            // Astragalos
            [729] = true,
            // Transparency
            [730] = true,
            // Territory #731
            [731] = false,
            // Eureka Anemos
            [732] = true,
            // The Binding Coil of Bahamut
            [733] = true,
            // The Royal City of Rabanastre
            [734] = true,
            // The Prima Vista Tiring Room
            [735] = false,
            // The Prima Vista Bridge
            [736] = false,
            // Royal Palace
            [737] = false,
            // The Resonatorium
            [738] = false,
            // The Doman Enclave
            [739] = false,
            // The Royal Menagerie
            [740] = false,
            // Sanctum of the Twelve
            [741] = true,
            // Hells' Lid
            [742] = true,
            // The Fractal Continuum
            [743] = true,
            // Kienkan
            [744] = false,
            // Territory #745
            [745] = false,
            // The Jade Stoa
            [746] = true,
            // Territory #747
            [747] = false,
            // Sigmascape V1.0
            [748] = true,
            // Sigmascape V2.0
            [749] = true,
            // Sigmascape V3.0
            [750] = true,
            // Sigmascape V4.0
            [751] = true,
            // Sigmascape V1.0
            [752] = true,
            // Sigmascape V2.0
            [753] = true,
            // Sigmascape V3.0
            [754] = true,
            // Sigmascape V4.0
            [755] = true,
            // The Interdimensional Rift
            [756] = false,
            // The Ruby Sea
            [757] = true,
            // The Jade Stoa
            [758] = true,
            // The Doman Enclave
            [759] = false,
            // The Fringes
            [760] = true,
            // The Great Hunt
            [761] = true,
            // The Great Hunt
            [762] = true,
            // Eureka Pagos
            [763] = true,
            // Reisen Temple
            [764] = false,
            // Territory #765
            [765] = false,
            // Territory #766
            [766] = false,
            // Territory #767
            [767] = false,
            // The Swallow's Compass
            [768] = true,
            // The Burn
            [769] = true,
            // Heaven-on-High
            [770] = true,
            // Heaven-on-High
            [771] = true,
            // Heaven-on-High
            [772] = true,
            // Heaven-on-High
            [773] = true,
            // Heaven-on-High
            [774] = true,
            // Heaven-on-High
            [775] = true,
            // The Ridorana Lighthouse
            [776] = true,
            // Ultimacy
            [777] = true,
            // Castrum Fluminis
            [778] = true,
            // Castrum Fluminis
            [779] = true,
            // Heaven-on-High
            [780] = false,
            // Reisen Temple Road
            [781] = true,
            // Heaven-on-High
            [782] = true,
            // Heaven-on-High
            [783] = true,
            // Heaven-on-High
            [784] = true,
            // Heaven-on-High
            [785] = true,
            // Castrum Fluminis
            [786] = false,
            // The Ridorana Cataract
            [787] = false,
            // Saint Mocianne's Arboretum
            [788] = true,
            // Territory #789
            [789] = false,
            // Ul'dah - Steps of Nald
            [790] = true,
            // Hidden Gorge
            [791] = true,
            // The Fall of Belah'dia
            [792] = true,
            // Territory #793
            [793] = false,
            // The Shifting Altars of Uznair
            [794] = true,
            // Eureka Pyros
            [795] = true,
            // Blue Sky
            [796] = true,
            // The Azim Steppe
            [797] = true,
            // Psiscape V1.0
            [798] = true,
            // Psiscape V2.0
            [799] = true,
            // The Interdimensional Rift
            [800] = true,
            // The Interdimensional Rift
            [801] = true,
            // Psiscape V1.0
            [802] = true,
            // Psiscape V2.0
            [803] = true,
            // The Interdimensional Rift
            [804] = true,
            // The Interdimensional Rift
            [805] = true,
            // Kugane Ohashi
            [806] = true,
            // The Interdimensional Rift
            [807] = false,
            // The Interdimensional Rift
            [808] = false,
            // Haunted Manor
            [809] = false,
            // Hells' Kier
            [810] = true,
            // Hells' Kier
            [811] = true,
            // The Interdimensional Rift
            [812] = false,
            // Lakeland
            [813] = false,
            // Kholusia
            [814] = false,
            // Amh Araeng
            [815] = false,
            // Il Mheg
            [816] = false,
            // The Rak'tika Greatwood
            [817] = false,
            // The Tempest
            [818] = false,
            // The Crystarium
            [819] = false,
            // Eulmore
            [820] = false,
            // Dohn Mheg
            [821] = true,
            // Mt. Gulg
            [822] = true,
            // The Qitana Ravel
            [823] = true,
            // The Wreath of Snakes
            [824] = true,
            // The Wreath of Snakes
            [825] = true,
            // The Orbonne Monastery
            [826] = true,
            // Eureka Hydatos
            [827] = true,
            // The Prima Vista Tiring Room
            [828] = false,
            // Eorzean Alliance Headquarters
            [829] = false,
            // The Ghimlyt Dark
            [830] = true,
            // The Manderville Tables
            [831] = true,
            // The Gold Saucer
            [832] = true,
            // The Howling Eye
            [833] = false,
            // The Howling Eye
            [834] = true,
            // Territory #835
            [835] = false,
            // Malikah's Well
            [836] = true,
            // Holminster Switch
            [837] = true,
            // Amaurot
            [838] = true,
            // East Shroud
            [839] = true,
            // The Twinning
            [840] = true,
            // Akadaemia Anyder
            [841] = true,
            // The Syrcus Trench
            [842] = false,
            // The Pendants Personal Suite
            [843] = true,
            // The Ocular
            [844] = false,
            // The Dancing Plague
            [845] = true,
            // The Crown of the Immaculate
            [846] = true,
            // The Dying Gasp
            [847] = true,
            // The Crown of the Immaculate
            [848] = true,
            // The Core
            [849] = true,
            // The Halo
            [850] = true,
            // The Nereus Trench
            [851] = true,
            // Atlas Peak
            [852] = true,
            // The Core
            [853] = true,
            // The Halo
            [854] = true,
            // The Nereus Trench
            [855] = true,
            // Atlas Peak
            [856] = true,
            // The Core
            [857] = false,
            // The Dancing Plague
            [858] = true,
            // The Confessional of Toupasa the Elder
            [859] = true,
            // Amh Araeng
            [860] = true,
            // Lakeland
            [861] = true,
            // Lakeland
            [862] = true,
            // Eulmore
            [863] = true,
            // Kholusia
            [864] = true,
            // Old Gridania
            [865] = true,
            // Coerthas Western Highlands
            [866] = true,
            // Eastern La Noscea
            [867] = true,
            // The Peaks
            [868] = true,
            // Il Mheg
            [869] = true,
            // Kholusia
            [870] = true,
            // The Rak'tika Greatwood
            [871] = true,
            // Amh Araeng
            [872] = true,
            // The Dancing Plague
            [873] = true,
            // The Rak'tika Greatwood
            [874] = true,
            // The Rak'tika Greatwood
            [875] = true,
            // The Nabaath Mines
            [876] = true,
            // Lakeland
            [877] = false,
            // The Empty
            [878] = false,
            // The Dungeons of Lyhe Ghiah
            [879] = true,
            // The Crown of the Immaculate
            [880] = false,
            // The Dying Gasp
            [881] = false,
            // The Copied Factory
            [882] = true,
            // Territory #883
            [883] = false,
            // The Grand Cosmos
            [884] = true,
            // The Dying Gasp
            [885] = true,
            // The Firmament
            [886] = false,
            // Liminal Space
            [887] = true,
            // Onsal Hakair
            [888] = true,
            // Lyhe Mheg
            [889] = false,
            // Lyhe Mheg
            [890] = false,
            // Lyhe Mheg
            [891] = false,
            // Lyhe Mheg
            [892] = false,
            // The Imperial Palace
            [893] = true,
            // Lyhe Mheg
            [894] = true,
            // Excavation Tunnels
            [895] = false,
            // The Copied Factory
            [896] = false,
            // Cinder Drift
            [897] = true,
            // Anamnesis Anyder
            [898] = true,
            // The Falling City of Nym
            [899] = true,
            // The Endeavor
            [900] = true,
            // The Diadem
            [901] = true,
            // The Gandof Thunder Plains
            [902] = true,
            // Ashfall
            [903] = true,
            // The Halo
            [904] = true,
            // Great Glacier
            [905] = true,
            // The Gandof Thunder Plains
            [906] = true,
            // Ashfall
            [907] = true,
            // The Halo
            [908] = true,
            // Great Glacier
            [909] = true,
            // Territory #910
            [910] = false,
            // Cid's Memory
            [911] = true,
            // Cinder Drift
            [912] = true,
            // Transmission Control
            [913] = true,
            // Trial's Threshold
            [914] = true,
            // Gangos
            [915] = false,
            // The Heroes' Gauntlet
            [916] = true,
            // The Puppets' Bunker
            [917] = true,
            // Anamnesis Anyder
            [918] = false,
            // Terncliff
            [919] = false,
            // Bozjan Southern Front
            [920] = true,
            // Frondale's Home for Friendless Foundlings
            [921] = false,
            // The Seat of Sacrifice
            [922] = true,
            // The Seat of Sacrifice
            [923] = true,
            // The Shifting Oubliettes of Lyhe Ghiah
            [924] = true,
            // Terncliff Bay
            [925] = true,
            // Terncliff Bay
            [926] = true,
            // Territory #927
            [927] = false,
            // The Puppets' Bunker
            [928] = false,
            // The Diadem
            [929] = true,
            // Territory #930
            [930] = false,
            // The Seat of Sacrifice
            [931] = false,
            // The Tempest
            [932] = true,
            // Matoya's Relict
            [933] = true,
            // Castrum Marinum Drydocks
            [934] = true,
            // Castrum Marinum Drydocks
            [935] = true,
            // Delubrum Reginae
            [936] = true,
            // Delubrum Reginae
            [937] = true,
            // Paglth'an
            [938] = true,
            // The Diadem
            [939] = true,
            // The Battlehall
            [940] = true,
            // The Battlehall
            [941] = true,
            // Sphere of Naught
            [942] = true,
            // Laxan Loft
            [943] = true,
            // Bygone Gaol
            [944] = true,
            // The Garden of Nowhere
            [945] = true,
            // Sphere of Naught
            [946] = true,
            // Laxan Loft
            [947] = true,
            // Bygone Gaol
            [948] = true,
            // The Garden of Nowhere
            [949] = true,
            // G-Savior Deck
            [950] = true,
            // G-Savior Deck
            [951] = true,
            // The Tower of Zot
            [952] = true,
            // Territory #953
            [953] = false,
            // The Navel
            [954] = true,
            // The Last Trace
            [955] = true,
            // Labyrinthos
            [956] = false,
            // Thavnair
            [957] = false,
            // Garlemald
            [958] = false,
            // Mare Lamentorum
            [959] = false,
            // Ultima Thule
            [960] = false,
            // Elpis
            [961] = false,
            // Old Sharlayan
            [962] = false,
            // Radz-at-Han
            [963] = false,
            // The Last Trace
            [964] = false,
            // The Empty
            [965] = false,
            // The Tower at Paradigm's Breach
            [966] = true,
            // Castrum Marinum Drydocks
            [967] = false,
            // Medias Res
            [968] = true,
            // The Tower of Babil
            [969] = true,
            // Vanaspati
            [970] = true,
            // Lemures Headquarters
            [971] = false,
            // Territory #972
            [972] = false,
            // The Dead Ends
            [973] = true,
            // Ktisis Hyperboreia
            [974] = true,
            // Zadnor
            [975] = true,
            // Smileton
            [976] = true,
            // Carteneau Flats: Borderland Ruins
            [977] = true,
            // The Aitiascope
            [978] = true,
            // Empyreum
            [979] = false,
            // Private Cottage - Empyreum
            [980] = false,
            // Private House - Empyreum
            [981] = false,
            // Private Mansion - Empyreum
            [982] = false,
            // Private Chambers - Empyreum
            [983] = false,
            // Company Workshop - Empyreum
            [984] = true,
            // Ingleside Apartment Lobby
            [985] = false,
            // The Stigma Dreamscape
            [986] = true,
            // Main Hall
            [987] = false,
            // m5e1
            [988] = false,
            // k5e2
            [989] = false,
            // Andron
            [990] = true,
            // G-Savior Deck
            [991] = false,
            // The Dark Inside
            [992] = true,
            // The Dark Inside
            [993] = true,
            // The Phantoms' Feast
            [994] = true,
            // The Mothercrystal
            [995] = true,
            // The Mothercrystal
            [996] = true,
            // The Final Day
            [997] = true,
            // The Final Day
            [998] = true,
            // Ingleside Apartment
            [999] = false,
            // The Excitatron 6000
            [1000] = true,
            // Strategy Room
            [1001] = false,
            // The Gates of Pandæmonium
            [1002] = true,
            // The Gates of Pandæmonium
            [1003] = true,
            // The Stagnant Limbo
            [1004] = true,
            // The Stagnant Limbo
            [1005] = true,
            // The Fervid Limbo
            [1006] = true,
            // The Fervid Limbo
            [1007] = true,
            // The Sanguine Limbo
            [1008] = true,
            // The Sanguine Limbo
            [1009] = true,
            // Magna Glacies
            [1010] = true,
            // Garlemald
            [1011] = true,
            // Magna Glacies
            [1012] = true,
            // Beyond the Stars
            [1013] = true,
            // Elpis
            [1014] = true,
            // Central Shroud
            [1015] = true,
            // Sastasha
            [1016] = true,
            // The Swallow's Compass
            [1017] = true,
            // The Vault
            [1018] = true,
            // The Peaks
            [1019] = true,
            // Cutter's Cry
            [1020] = true,
            // Dusk Vigil
            [1021] = true,
            // Saint Mocianne's Arboretum
            [1022] = true,
            // The Dravanian Forelands
            [1023] = true,
            // The Nethergate
            [1024] = false,
            // The Gates of Pandæmonium
            [1025] = false,
            // Beyond the Stars
            [1026] = false,
            // Ultima Thule
            [1027] = false,
            // The Dark Inside
            [1028] = false,
            // The Final Day
            [1029] = false,
            // The Mothercrystal
            [1030] = false,
            // Propylaion
            [1031] = false,
            // The Palaistra
            [1032] = true,
            // The Volcanic Heart
            [1033] = true,
            // Cloud Nine
            [1034] = true,
            // Territory #1035
            [1035] = false,
            // Sastasha
            [1036] = true,
            // The Tam-Tara Deepcroft
            [1037] = true,
            // Copperbell Mines
            [1038] = true,
            // The Thousand Maws of Toto-Rak
            [1039] = true,
            // Haukke Manor
            [1040] = true,
            // Brayflox's Longstop
            [1041] = true,
            // Stone Vigil
            [1042] = true,
            // Castrum Meridianum
            [1043] = true,
            // The Praetorium
            [1044] = true,
            // Bowl of Embers
            [1045] = true,
            // The Navel
            [1046] = true,
            // The Howling Eye
            [1047] = true,
            // Porta Decumana
            [1048] = true,
            // Western Thanalan
            [1049] = true,
            // Alzadaal's Legacy
            [1050] = true,
            // The Tower of Babil
            [1051] = true,
            // The Porta Decumana
            [1052] = true,
            // The Porta Decumana
            [1053] = false,
            // Aglaia
            [1054] = true,
            // Unnamed Island
            [1055] = true,
            // Alzadaal's Legacy
            [1056] = false,
            // Restricted Archives
            [1057] = false,
            // The Palaistra
            [1058] = true,
            // The Volcanic Heart
            [1059] = true,
            // Cloud Nine
            [1060] = true,
            // The Omphalos
            [1061] = false,
            // Snowcloak
            [1062] = true,
            // The Keeper of the Lake
            [1063] = true,
            // Sohm Al
            [1064] = true,
            // The Aery
            [1065] = true,
            // The Vault
            [1066] = true,
            // Thornmarch
            [1067] = true,
            // Steps of Faith
            [1068] = true,
            // The Sil'dihn Subterrane
            [1069] = true,
            // The Fell Court of Troia
            [1070] = true,
            // Storm's Crown
            [1071] = true,
            // Storm's Crown
            [1072] = true,
            // Elysion
            [1073] = false,
            // Territory #1074
            [1074] = false,
            // Another Sil'dihn Subterrane
            [1075] = true,
            // Another Sil'dihn Subterrane
            [1076] = true,
            // Zero's Domain
            [1077] = false,
            // Meghaduta Guest Chambers
            [1078] = false,
            // The Aitiascope
            [1079] = false,
            // Territory #1080
            [1080] = false,
            // The Caustic Purgatory
            [1081] = true,
            // The Caustic Purgatory
            [1082] = true,
            // The Pestilent Purgatory
            [1083] = true,
            // The Pestilent Purgatory
            [1084] = true,
            // The Hollow Purgatory
            [1085] = true,
            // The Hollow Purgatory
            [1086] = true,
            // Stygian Insenescence Cells
            [1087] = true,
            // Stygian Insenescence Cells
            [1088] = true,
            // The Fell Court of Troia
            [1089] = false,
            // Territory #1090
            [1090] = false,
            // The Fell Court of Troia
            [1091] = true,
            // Storm's Crown
            [1092] = false,
            // Stygian Insenescence Cells
            [1093] = false,
            // Sneaky Hollow
            [1094] = false,
            // Mount Ordeals
            [1095] = true,
            // Mount Ordeals
            [1096] = true,
            // Lapis Manalis
            [1097] = true,
            // Sylphstep
            [1098] = true,
            // Eureka Orthos
            [1099] = true,
            // Eureka Orthos
            [1100] = true,
            // Eureka Orthos
            [1101] = true,
            // Eureka Orthos
            [1102] = true,
            // Eureka Orthos
            [1103] = true,
            // Eureka Orthos
            [1104] = true,
            // Eureka Orthos
            [1105] = true,
            // Eureka Orthos
            [1106] = true,
            // Eureka Orthos
            [1107] = true,
            // Eureka Orthos
            [1108] = true,
            // The Great Gubal Library
            [1109] = true,
            // Aetherochemical Research Facility
            [1110] = true,
            // The Antitower
            [1111] = true,
            // Sohr Khai
            [1112] = true,
            // Xelphatol
            [1113] = true,
            // Baelsar's Wall
            [1114] = true,
            // The Tower of Babil
            [1115] = true,
            // The Clockwork Castletown
            [1116] = true,
            // The Clockwork Castletown
            [1117] = true,
            // Euphrosyne
            [1118] = true,
            // Lapis Manalis
            [1119] = false,
            // Garlemald
            [1120] = true,
            // Territory #1121
            [1121] = false,
            // The Interdimensional Rift
            [1122] = true,
            // The Shifting Gymnasion Agonon
            [1123] = true,
            // Eureka Orthos
            [1124] = false,
            // Khadga
            [1125] = false,
            // The Aetherfont
            [1126] = true,
            // The Fold
            [1127] = true,
            // The Fold
            [1128] = true,
            // The Fold
            [1129] = true,
            // Territory #1130
            [1130] = false,
            // Territory #1131
            [1131] = false,
            // Territory #1132
            [1132] = false,
            // Territory #1133
            [1133] = false,
            // Territory #1134
            [1134] = false,
            // Territory #1135
            [1135] = false,
            // The Gilded Araya
            [1136] = true,
            // Mount Rokkon
            [1137] = true,
            // The Red Sands
            [1138] = true,
            // The Red Sands
            [1139] = true,
            // The Voidcast Dais
            [1140] = true,
            // The Voidcast Dais
            [1141] = true,
            // The Sirensong Sea
            [1142] = true,
            // Bardam's Mettle
            [1143] = true,
            // Doma Castle
            [1144] = true,
            // Castrum Abania
            [1145] = true,
            // Ala Mhigo
            [1146] = true,
            // The Aetherial Slough
            [1147] = true,
            // The Aetherial Slough
            [1148] = true,
            // The Dæmons' Nest
            [1149] = true,
            // The Dæmons' Nest
            [1150] = true,
            // The Chamber of Fourteen
            [1151] = true,
            // The Chamber of Fourteen
            [1152] = true,
            // Ascension
            [1153] = true,
            // Ascension
            [1154] = true,
            // Another Mount Rokkon
            [1155] = true,
            // Another Mount Rokkon
            [1156] = true,
            // Territory #1157
            [1157] = false,
            // The Dæmons' Nest
            [1158] = false,
            // The Voidcast Dais
            [1159] = false,
            // Senatus
            [1160] = false,
            // Estinien's Chambers
            [1161] = false,
            // The Red Moon
            [1162] = false,
            // The Endeavor
            [1163] = true,
            // The Lunar Subterrane
            [1164] = true,
            // Blunderville
            [1165] = true,
            // The Memory of Embers
            [1166] = true,
            // Ihuykatumu
            [1167] = true,
            // The Abyssal Fracture
            [1168] = true,
            // The Abyssal Fracture
            [1169] = true,
            // Sunperch
            [1170] = false,
            // Earthen Sky Hideout
            [1171] = false,
            // The Drowned City of Skalla
            [1172] = true,
            // The Burn
            [1173] = true,
            // The Ghimlyt Dark
            [1174] = true,
            // Territory #1175
            [1175] = false,
            // Aloalo Island
            [1176] = true,
            // The Aetherfont
            [1177] = true,
            // Thaleia
            [1178] = true,
            // Another Aloalo Island
            [1179] = true,
            // Another Aloalo Island
            [1180] = true,
            // The Abyssal Fracture
            [1181] = false,
            // Thaleia
            [1182] = false,
            // The Gilded Araya
            [1183] = false,
            // The Lunar Subterrane
            [1184] = false,
            // Tuliyollal
            [1185] = false,
            // Solution Nine
            [1186] = false,
            // Urqopacha
            [1187] = false,
            // Kozama'uka
            [1188] = false,
            // Yak T'el
            [1189] = false,
            // Shaaloani
            [1190] = false,
            // Heritage Found
            [1191] = false,
            // Living Memory
            [1192] = false,
            // Worqor Zormor
            [1193] = true,
            // The Skydeep Cenote
            [1194] = true,
            // Worqor Lar Dor
            [1195] = true,
            // Worqor Lar Dor
            [1196] = true,
            // Blunderville Square
            [1197] = false,
            // Vanguard
            [1198] = true,
            // Alexandria
            [1199] = true,
            // Summit of Everkeep
            [1200] = true,
            // Summit of Everkeep
            [1201] = true,
            // Interphos
            [1202] = true,
            // Tender Valley
            [1203] = true,
            // Strayborough
            [1204] = true,
            // The For'ard Cabins
            [1205] = true,
            // Main Deck
            [1206] = false,
            // The Backroom
            [1207] = false,
            // Origenics
            [1208] = true,
            // Cenote Ja Ja Gural
            [1209] = true,
            // Sunperch
            [1210] = true,
            // Yak T'el
            [1211] = true,
            // Yak T'el
            [1212] = true,
            // Solution Nine
            [1213] = true,
            // The Sea of Clouds
            [1214] = true,
            // Brayflox's Longstop
            [1215] = true,
            // Bardam's Mettle
            [1216] = true,
            // Ala Mhigo
            [1217] = true,
            // Khadga
            [1218] = true,
            // Vanguard
            [1219] = false,
            // Summit of Everkeep
            [1220] = false,
            // Interphos
            [1221] = false,
            // Skydeep Cenote Inner Chamber
            [1222] = false,
            // Tritails Training
            [1223] = false,
            // Greenroom
            [1224] = false,
            // Scratching Ring
            [1225] = true,
            // Scratching Ring
            [1226] = true,
            // Lovely Lovering
            [1227] = true,
            // Lovely Lovering
            [1228] = true,
            // Blasting Ring
            [1229] = true,
            // Blasting Ring
            [1230] = true,
            // The Thundering
            [1231] = true,
            // The Thundering
            [1232] = true,
            // Manor Basement
            [1233] = true,
            // Dreamlike Palace
            [1234] = true,
            // Central Thanalan
            [1235] = true,
            // Southern Thanalan
            [1236] = true,
            // Sinus Ardorum
            [1237] = false,
            // A Future Rewritten
            [1238] = true,
            // Territory #1239
            [1239] = false,
            // Territory #1240
            [1240] = false,
            // Sphere of Naught
            [1241] = true,
            // Yuweyawata
            [1242] = true,
            // Interphos
            [1243] = true,
            // Shaaloani
            [1244] = true,
            // Halatali
            [1245] = true,
            // Zorgor the Boundless
            [1246] = true,
            // Starlight Stalls
            [1247] = false,
            // Jeuno: The First Walk
            [1248] = true,
            // h1i1
            [1249] = false,
            // h1i2
            [1250] = false,
            // h1i3
            [1251] = false,
            // South Horn
            [1252] = true,
            // Starlight Stalls
            [1253] = false,
            // Yuweyawata
            [1254] = false,
            // Hall of the Unbound
            [1255] = false,
            // Groovy Ring
            [1256] = true,
            // Groovy Ring
            [1257] = true,
            // Rebel Ring
            [1258] = true,
            // Rebel Ring
            [1259] = true,
            // Demolition Site
            [1260] = true,
            // Demolition Site
            [1261] = true,
            // Hunter's Ring
            [1262] = true,
            // Hunter's Ring
            [1263] = true,
            // Lower Jeuno
            [1264] = false,
            // Lower Jeuno
            [1265] = false,
            // The Underkeep
            [1266] = true,
            // The Sunken Temple of Qarn
            [1267] = true,
            // Break Room
            [1268] = false,
            // Phantom Village
            [1269] = false,
            // Recollection
            [1270] = true,
            // Recollection
            [1271] = true,
            // Territory #1272
            [1272] = false,
            // Carteneau Flats: Borderland Ruins
            [1273] = true,
            // Throne Room
            [1274] = false,
            // Recollection
            [1275] = false,
            // Demolition Site
            [1276] = false,
            // Main Deck
            [1277] = false,
            // Phantom Village
            [1278] = false,
            // Vault Oneiron
            [1279] = true,
            // Territory #1280
            [1280] = false,
            // Territory #1281
            [1281] = false,
            // Territory #1282
            [1282] = false,
            // Territory #1283
            [1283] = false,
            // Territory #1284
            [1284] = false,
            // Territory #1285
            [1285] = false,
            // Territory #1286
            [1286] = false,
            // Territory #1287
            [1287] = false,
            // Territory #1288
            [1288] = false,
            // Territory #1289
            [1289] = false,
            // Territory #1290
            [1290] = false,
            // Phaenna
            [1291] = false,
            // The Meso Terminal
            [1292] = true,
            // The Bayside Battleground
            [1293] = true,
            // The Bayside Battleground
            [1294] = true,
            // The Ageless Necropolis
            [1295] = true,
            // The Ageless Necropolis
            [1296] = true,
            // Territory #1297
            [1297] = false,
            // Territory #1298
            [1298] = false,
            // Containment Complex 10-29
            [1299] = false,
            // Territory #1300
            [1300] = false,
            // Territory #1301
            [1301] = false,
            // The Wreath of Snakes
            [1302] = true,
            // Cutter's Cry
            [1303] = true,
            // San d'Oria: The Second Walk
            [1304] = true,
            // Haunted Manor
            [1305] = false,
            // Territory #1306
            [1306] = false,
            // Territory #1307
            [1307] = false,
            // Territory #1308
            [1308] = false,
            // Starlight Stalls
            [1309] = false,
            // Territory #1310
            [1310] = false,
            // Territory #1311
            [1311] = false,
            // The Ageless Necropolis
            [1312] = false,
            // Territory #1313
            [1313] = false,
            // Territory #1314
            [1314] = false,
            // Territory #1315
            [1315] = false,
            // Territory #1316
            [1316] = false,
            // Territory #1317
            [1317] = false,
            // Territory #1318
            [1318] = false,
            // Territory #1319
            [1319] = false,
            // Territory #1320
            [1320] = false,
            // Territory #1321
            [1321] = false,
            // Territory #1322
            [1322] = false,
            // Territory #1323
            [1323] = false,
            // Territory #1324
            [1324] = false,
            // Territory #1325
            [1325] = false,
            // Territory #1326
            [1326] = false,
            // Territory #1327
            [1327] = false,
            // Territory #1328
            [1328] = false,
            // Territory #1329
            [1329] = false,
            // Territory #1330
            [1330] = false,
            // Territory #1331
            [1331] = false,
            // Territory #1332
            [1332] = false,
            // Territory #1333
            [1333] = false,
        };
    }
}
